-- insert into artist(name)
-- values('Tyler Childers'),
-- ('Zach Bryan'),
-- ('Cody Johnson')
-- select * from artist
-- order by name desc
-- limit 10
-- select * from artist
-- order by name 
-- limit 5
-- select * from artist
-- where name like 'Black%';
-- select * from artist
-- where name like '%Black%';