select * from invoice 
--select count (*) from invoice
-- where billing_country ='USA'
-- select total from invoice
-- order by total desc
-- limit 1
-- select total from invoice
-- order by total 
-- limit 1
-- select * from invoice 
-- where total > 5
-- order by total;
-- select count (*) from invoice 
-- where total < 5
-- select count (*) from invoice
-- where billing_state IN ('CA', 'TX', 'AZ')
-- select avg(total) from invoice
-- select sum(total) from invoice
-- update invoice
-- set total = 24
-- where invoice_id = 5
-- DELETE
-- FROM invoice_line
-- WHERE invoice_id = 1;
-- DELETE
-- FROM invoice
-- WHERE invoice_id = 1;