 create table orders(
-- 	order_id SERIAL PRIMARY KEY,
-- 	person_id SERIAL,
--   product_name VARCHAR(30) not null,
--   product_price float, 
--   quantity int
-- );
-- INSERT INTO orders(product_name, product_price, quantity)
-- VALUES('shoes', 19.99, 1),
-- ('shirt', 15.99, 2),
-- ('pants', 18.99, 3),
-- ('hat', 13.99, 5),
-- ('sunglasses', 9.99, 4)
-- select * from orders;
-- select sum(quantity) from orders
-- select sum(product_price * quantity) from orders
-- select sum(product_price * quantity) from orders
-- where person_id = 3;